models:
  - type: main
    engine: openai
    model: openai.gpt-4.1
    api_key_env_var: OPENAI_API_KEY
    parameters:
      temperature: 0
      base_url: https://inference.generativeai.us-chicago-1.oci.oraclecloud.com/20231130/actions/v1
      max_tokens: 50   # 🔥 evita respostas longas do LLM

  # 🔥 usado apenas se você chamar explicitamente no flow
  - type: self_check_input
    engine: openai
    model: openai.gpt-4.1
    api_key_env_var: OPENAI_API_KEY
    parameters:
      temperature: 0
      base_url: https://inference.generativeai.us-chicago-1.oci.oraclecloud.com/20231130/actions/v1


rails:
  input:
    flows:
      - check_input_terms
  output:
    flows:
      - check_output_terms
